const Task = require("../models/Task");

/**
 * Tool 1: Fetches all currently pending tasks (Todo or In Progress) from MongoDB.
 * Populates assignee and workspace details to provide rich context for the AI.
 * @returns {Promise<Array>} A list of pending tasks.
 */
async function fetchPendingTasks() {
  try {
    const tasks = await Task.find({
      status: { $in: ["todo", "in-progress"] }
    })
      .populate("assignedTo", "name email role")
      .populate("workspaceId", "title description")
      .lean();
    return tasks;
  } catch (error) {
    console.error("Error inside fetchPendingTasks tool:", error);
    throw error;
  }
}

/**
 * Tool 2: Updates a task in the database with AI-generated metadata.
 * @param {string} taskId - The Mongoose ObjectId of the task.
 * @param {Object} metadata - AI metadata fields.
 * @param {Array<string>} metadata.aiSubTasks - The 3 subtasks generated by Gemini.
 * @param {number} metadata.aiRiskScore - The completion risk percentage (0 to 100).
 * @param {string} metadata.aiSummary - The short diagnostic summary.
 * @returns {Promise<Object>} The updated task document.
 */
async function updateTaskAIMetadata(taskId, { aiSubTasks, aiRiskScore, aiSummary }) {
  try {
    const updatedTask = await Task.findByIdAndUpdate(
      taskId,
      {
        aiSubTasks,
        aiRiskScore,
        aiSummary
      },
      { new: true } // Returns the modified document
    )
      .populate("assignedTo", "name email role")
      .populate("workspaceId", "title description")
      .lean();
    return updatedTask;
  } catch (error) {
    console.error(`Error inside updateTaskAIMetadata tool for Task ${taskId}:`, error);
    throw error;
  }
}

module.exports = {
  fetchPendingTasks,
  updateTaskAIMetadata
};
